### ISSUE TITLE
500 when creating a new user

### ISSUE THREAD

**Issue by tachyons** [smc/grandham#27]
![screenshot from 2015-02-04 10 47 49](https://cloud.githubusercontent.com/assets/3112976/6035524/610cb8f0-ac5b-11e4-91eb-62e510c43e3a.png)

**Comment by maheshm** [comment]
@tachyons Can you add some more details please?

**Comment by tachyons** [comment]
when tried to signup in the website

**Comment by ershad** [comment]
The transactional email configuration is missing, let me fix that now.
