### ISSUE TITLE
Travis Build is failing 

### ISSUE THREAD

**Issue by maheshm** [smc/grandham#29]
`An error occurred while installing jquery-datatables-rails (1.12.2), and Bundler`

**Comment by maheshm** [comment]
Way too old, probably use latest (3.3.0)

**Comment by Roshanjossey** [comment]
There are also some specs that are failing that needs to be fixed.

**Comment by maheshm** [comment]
@Roshanjossey Can you do a pastebin dump of the failure please?

**Comment by Roshanjossey** [comment]
@maheshm: Here's the pastebin dump
[http://pastebin.com/9PruAaBA](http://pastebin.com/9PruAaBA)

We don't need the files 
/spec/helpers/library_helper_spec.rb,
/spec/helpers/publisher_helper_spec.rb
anymore.

Also we need to update specs for Search model and BooksController specs

**Comment by maheshm** [comment]
@ershad Any idea why helper specs might be failing? Seems fine to me.
@Roshanjossey Can you please update the search and books specs?

**Comment by Roshanjossey** [comment]
@maheshm: One problem is that search specs doesn't make much sense to me. Could you give me more information about how it's supposed to work?

**Comment by Roshanjossey** [comment]
@maheshm, @ershad: Is there a way to try building with Travis without submitting a pr? Or is submitting pr the preferred way?

**Comment by tachyons** [comment]
@Roshanjossey you can the test case in your local machine , or you can use another travis ci link for your clone . Submitting pr without verifying the test case isn't good

**Comment by Roshanjossey** [comment]
@tachyons: Thank you. I think I'll use a different travis ci link. I was not concerned about the specs but things like bundle failing. I can't bundle errors on my machine.

**Comment by Roshanjossey** [comment]
I think we resolved this issue in #31. @maheshm, @ershad, @tachyons:  could you share your thoughts on closing this issue.

**Comment by maheshm** [comment]
Closing.
