### ISSUE TITLE
www.grandham.org  is not available

### ISSUE THREAD

**Issue by manojkmohan** [smc/grandham#32]
The site is not available.

**Comment by maheshm** [comment]
@ershad Dude, it is still down, can you take a look at it please?

**Comment by ershad** [comment]
@manojkmohan @maheshm Sorry, I missed this thread. We had a donated server where we hosted Grandham, but it went down a few months ago. Recently we tried to host in another machine but RAM wasn't sufficient.

@anivar do we have a spare server to host this? I've a small server, will try to host it there but there's a high chance the application will be really slow.

**Comment by tachyons** [comment]
poke

**Comment by ershad** [comment]
@tachyons @anivar @anishsheela I checked the server I've, it's already running a couple of apps and there's no memory left enough to run Grandham. Do we have any spare server where we can run Grandham?

**Comment by anishsheela** [comment]
@ershad I can provide. I will pm the details.

**Comment by tachyons** [comment]
check grandham.in

**Comment by manojkmohan** [comment]
Thanks
